apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
data:
  MINIO_ACCESS_KEY: Y1F6UnhWOXQ0djlrYzlack5JVm8=
  MINIO_SECRET_KEY: MFg0a3d3NnBlU3BUYzY5TUwzb2MxYnpqUlFZVnJWbldWSzhOWkNRTw==
