version: '3'
services:
  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - "MINIO_ROOT_USER=dimanyumovich"
      - "MINIO_ROOT_PASSWORD=karnaval"
    command: server /data --console-address ":9001"
