apiVersion: apps/v1
kind: Deployment
metadata:
  name: dima-k8s-pod-deployment-replicas
  labels:
    app: my-k8s-application
    owner: DimaK
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      project: dima-k8s-pod-deployment-replicas
  template:
    metadata:
      labels:
        project: dima-k8s-pod-deployment-replicas
    spec:
      containers:
        - name: dima-k8s-container
          image: dimanyumovich/dima-k8s:v10
          ports:
            - containerPort: 5000
          env:
            - name: ACCESS_KEY
              value: "sKLw3zR5mODPq5nkxm1w"
            - name: SECRET_KEY
              value: "1GAF3EzGZwDRcYHHzfYP96vRkY71KjMiUQbmekkj"
            - name: ENDPOINT
              value: "http://192.168.59.1:9000"