apiVersion: v1
kind: Pod
metadata:
  name: dima-k8s-pod
spec:
  containers:
    - name: dima-k8s-container
      image: dimanyumovich/dima-k8s:v10
      ports:
        - containerPort: 5000
      env:
        - name: ACCESS_KEY
          value: "jDmWYPDWr2F4DOKeYHBZ"
        - name: SECRET_KEY
          value: "HBmcl8gqNKgOITTiX10wuyQnvHMoGkESppdy2F8U"
        - name: ENDPOINT
          value: "http://192.168.59.1:9000"