apiVersion: v1
kind: Pod
metadata:
  name: dima-k8s-pod
spec:
  containers:
    - name: dima-k8s-container
      image: dimanyumovich/dima-k8s:v10
      ports:
        - containerPort: 5000
      env:
        - name: ACCESS_KEY
          value: "aPz7w7k4k3sylLtvWW2s"
        - name: SECRET_KEY
          value: "M3kwshFvUqeR1J40KHeNiAmYFR2jBL7B1s4kQgvW"
        - name: ENDPOINT
          value: "http://192.168.159.1:9000"