apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-deployment
spec:
  replicas: 1  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
#      securityContext:
#        runAsUser: 1000
#        runAsGroup: 1000
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          imagePullPolicy: IfNotPresent  # You can set to "Always" if needed
          ports:
            - name: port-9000
              containerPort: 9000
            - name: port-9001
              containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              value: dimanyumovich
            - name: MINIO_ROOT_PASSWORD
              value: karnaval
#          volumeMounts:
#            - name: data
#              mountPath: /data
          command: ["minio"]
          args: ["server", "/data", "--console-address", ":9001"]
#      volumes:
#        - name: data
#          persistentVolumeClaim:
#            claimName: fileshare