apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: my-app
  labels:
    role : nginx
    owner: DimaK
spec:
  containers:
    - name : app
      image: nginx:1.25
      ports:
        - containerPort: 80

