apiVersion: v1
kind: Pod
metadata:
  name: minio-pod
spec:
  containers:
#    - name: nginx
#      image: nginx
#      ports:
#        - containerPort: 80
#      volumeMounts:
#        - mountPath: /usr/share/nginx/html/data
#          # - mountPath: /cache-2
#          name: cache-volume
#          subPath: data
    - name: minio
      image: quay.io/minio/minio:RELEASE.2023-09-04T19-57-37Z
      ports:
        - containerPort: 9000
        - containerPort: 9001
      env:
        - name: MINIO_ROOT_USER
          value: dimanyumovich
        - name: MINIO_ROOT_PASSWORD
          value: karnaval
#      volumeMounts:
#        - mountPath: /data/.minio.sys/log
#          name: cache-volume
#          subPath: data
#      command: ["minio"]
#      args: ["server", "/data", "--console-address", ":9001"]
      command:
        - "minio"
        - "server"
        - "/tmp"
        - "--console-address"
        - ":9001"
#  volumes:
#    - name: cache-volume
#      emptyDir: { }
