apiVersion: v1
kind: PersistentVolume
metadata:
  name: cc-pv-volume
  labels:
    type: local
    author: ccuser
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
 # persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /tmp
    server: 192.168.1.40
    readOnly: false