apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-nfs-share
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
#  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.40
    path: /mnt/nfs_share

