version: '3'
services:
  minio:
    image: bitnami/minio:latest
    container_name: minio
    user: root
    environment:
      - MINIO_ROOT_USER=dimanyumovich
      - MINIO_ROOT_PASSWORD=karnaval
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - /opt/minio:/bitnami/minio/data
